### ISSUE TITLE
CRYS_Data_Model not found in trade_model.php

### ISSUE THREAD

**Issue by acarlson1994** [tylerdiaz/Crysandrea#20]
PHP Fatal error:  Class 'CRYS_Data_Model' not found in /var/www/html/application/models/trades_model.php on line 5

Where is the application/core/CRYS_Model.php being included/loaded into the application?

**Comment by tylerdiaz** [comment]
@acarlson1994 What PHP version are you using? Code Igniter is meant to load them automatically.

**Comment by tylerdiaz** [comment]
@acarlson1994, did you get this resolved?

**Comment by sirjoshua** [comment]
It was never resolved. The model is not uploaded.
